"""Pytest plugin: prints which rules from docs/rules.md passed in this run.

`pytest --rules-report` also writes the table to docs/rules-status.md.
"""

from collections import defaultdict

import pytest

from tests.rules_catalog import ROOT, documented_rules
from tests.rules_pending import PENDING

STATUS_FILE = ROOT / "docs" / "rules-status.md"

_rules_by_test: dict[str, tuple[str, ...]] = {}
_outcomes: dict[str, list[tuple[str, str]]] = defaultdict(list)


def pytest_addoption(parser: pytest.Parser) -> None:
    parser.addoption("--rules-report", action="store_true", help="write docs/rules-status.md")


def pytest_collection_modifyitems(items: list[pytest.Item]) -> None:
    for item in items:
        ids = tuple(rule for mark in item.iter_markers("rule") for rule in mark.args)
        if ids:
            _rules_by_test[item.nodeid] = ids


def pytest_runtest_logreport(report: pytest.TestReport) -> None:
    rules = _rules_by_test.get(report.nodeid)
    if not rules:
        return
    finished = report.when == "call" or (report.when == "setup" and not report.passed)
    if not finished:
        return
    for rule in rules:
        _outcomes[rule].append((report.nodeid, report.outcome))


def _status(rule: str) -> str:
    if rule in PENDING:
        return "pending"
    results = [outcome for _, outcome in _outcomes.get(rule, [])]
    if not results:
        return "not run"
    if "failed" in results:
        return "FAIL"
    if all(outcome == "skipped" for outcome in results):
        return "skipped"
    return "pass"


def _table() -> list[str]:
    lines = ["| Rule | Status | Tests |", "| --- | --- | --- |"]
    for rule in documented_rules():
        tests = sorted({nodeid.split("::")[-1] for nodeid, _ in _outcomes.get(rule, [])})
        lines.append(f"| {rule} | {_status(rule)} | {', '.join(tests) or '-'} |")
    return lines


def pytest_terminal_summary(terminalreporter, config: pytest.Config) -> None:
    rules = documented_rules()
    counts: dict[str, int] = defaultdict(int)
    for rule in rules:
        counts[_status(rule)] += 1
    summary = ", ".join(f"{count} {status}" for status, count in sorted(counts.items()))
    terminalreporter.write_sep("-", f"rules: {len(rules)} documented; {summary}")
    if config.getoption("--rules-report"):
        header = [
            "# Rule status",
            "",
            "Generated by `pytest --rules-report`. Do not edit by hand.",
            "",
        ]
        STATUS_FILE.write_text("\n".join(header + _table()) + "\n", encoding="utf-8")
        terminalreporter.write_line(f"wrote {STATUS_FILE.relative_to(ROOT).as_posix()}")
